FROM amazonlinux:2

ENV CVM_WEB_TOP_DIR=/app/web
ENV PLOTTING_TOP_DIR=/usr/local/share/plotting
ENV ANACONDA3_TOP_DIR=/usr/local/share/anaconda3
ENV UCVM_TOP_DIR=/usr/local/share/ucvm
ENV UCVM_CVM_VOLUME=/usr/local/share/cvm_volume
ENV UCVM_CVM_LARGE_DATASET=/usr/local/share/ucvm/cvm-large-dataset 

ENV UCVM_SRC_PATH=$UCVM_TOP_DIR/src
ENV UCVM_INSTALL_PATH=$UCVM_TOP_DIR/install

WORKDIR /app

COPY . /app

COPY ./doc/cvm.conf /etc/httpd/conf.d/

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql yum perl 

RUN /app/setup/run-web-setup

RUN source $UCVM_INSTALL_PATH/conf/ucvm_env.sh

CMD ["apachectl", "-D", "FOREGROUND"]

