FROM amazonlinux:2

WORKDIR /app

COPY . /app

COPY ./doc/cvm.conf /etc/httpd/conf.d/
COPY ./custom-php.ini /etc/php.d/custom-php.ini

RUN yum install -y tar mkdir sudo which git wget

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql 

XX
RUN mkdir /home/postgres
RUN chown postgres /home/postgres
RUN su postgres -c /app/doc/run-as-postgres



CMD ["apachectl", "-D", "FOREGROUND"]

