# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile-postgis
      context: ./
    restart: always
    environment:
      name: edric
      POSTGRES_PASSWORD: example

  web:
    build:
      dockerfile: Dockerfile-web
      context: ./
    volumes:
        - ./cvm_volume:/usr/local/share/cvm_volume
    restart: always
    ports:
      - 8100:8081
      - 8101:80
