FROM amazonlinux:2

WORKDIR /app

COPY . /app

COPY ./doc/cvm.conf /etc/httpd/conf.d/

RUN yum install -y tar mkdir sudo which git wget

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql 


RUN ./setup/run-web-setup

CMD ["apachectl", "-D", "FOREGROUND"]

