#!/bin/bash

dropdb --if-exists CVM_db 
createdb CVM_db

psql postgresql://postgres:example@localhost/CVM_db << AAA

  CREATE EXTENSION postgis;
  SELECT PostGIS_Version();

#  \i '/home/postgres/CVM/sql/setup_model_schema.sql';
#  \i '/home/postgres/CVM/sql/setup_model_tb.sql';
#  \i '/home/postgres/CVM/sql/setup_meta_schema.sql';
#  \i '/home/postgres/CVM/sql/setup_meta_tb.sql';
#  \i '/home/postgres/CVM/sql/linkup_traces.sql';

  DROP ROLE webonly;
  CREATE ROLE webonly WITH LOGIN PASSWORD 'scec';
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO webonly;
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  \dp
  \q

AAA

