#!/bin/bash
# run-build-ucvm

source setup/setup_cvm_web.sh

mkdir -p $UCVM_TOP_DIR
mkdir -p $UCVM_INSTALL_PATH

cd $UCVM_TOP_DIR
#git clone https://github.com/SCECcode/ucvm.git -b withSFCVM src
git clone https://github.com/SCECcode/ucvm.git -b testMei src

cd $UCVM_SRC_PATH/largefiles
./get_largefiles.py -m sfcvm,cca,cvmsi
./check_largefiles_md5.py
./stage_largefiles.py

cd $UCVM_SRC_PATH
./ucvm_setup.py -a -d -p $UCVM_INSTALL_PATH &> ucvm_setup_install.log

#cd $UCVM_SRC_PATH; make runcheck

## make sure everything in installed model is globally readable
chmod -R og+r $UCVM_INSTALL_PATH/model
echo "..done run-build-ucvm.."
