#!/bin/bash
# run-build-ucvm

source setup/setup_cvm_web.sh

mkdir -p $UCVM_TOP_DIR
mkdir -p $UCVM_INSTALL_PATH

cd $UCVM_TOP_DIR
#git clone https://github.com/SCECcode/ucvm.git -b withSFCVM src
git clone https://github.com/SCECcode/ucvm.git -b testMei src


cd $UCVM_SRC_PATH/largefiles
#./get_largefiles.py -m cs248,sfcvm,cvmh
./get_largefiles.py -m wfcvm,cca,sfcvm,cvms,cvmsi,cvms5,cvmh,ivlsu,cvlsu,albacore,sjfz,cvmhlabn,cvmhsgbn,cvmhvbn,cvmhibbn,cvmhrbn,cvmhsbbn,cvmhsbcbn,cvmhsmbn,cvmhstbn,cs248,canvas,uwsfbcvm,uwlinca
#./get_largefiles.py -m cvmh
./check_largefiles_md5.py
./stage_largefiles.py


cd $UCVM_SRC_PATH
./ucvm_setup.py -a -d -p $UCVM_INSTALL_PATH &> ucvm_setup_install.log

#cd $UCVM_SRC_PATH; make runcheck

## make sure everything in installed model is globally readable
chmod -R og+r $UCVM_INSTALL_PATH/model
echo "..done run-build-ucvm.."
